export default {
  CLIENTS_LOADED_SUCCESS: 'CLIENTS_LOADED_SUCCESS',
  LOAD_CLIENTS: 'LOAD_CLIENTS',

  RESIDENCES_LOADED_SUCCESS: 'RESIDENCES_LOADED_SUCCESS',
  LOAD_RESIDENCES: 'LOAD_RESIDENCES',

  CREATE_CLIENT: 'CREATE_CLIENT',
  CLIENT_CREATED_SUCCESS: 'CLIENT_CREATED_SUCCESS',

  UPDATE_CLIENT: 'UPDATE_CLIENT',
  CLIENT_UPDATED_SUCCESS: 'CLIENT_UPDATED_SUCCESS',

  CREATE_RESIDENCE: 'CREATE_RESIDENCE',
  RESIDENCE_CREATED_SUCCESS: 'RESIDENCE_CREATED_SUCCESS',

  DELETE_CLIENT: 'DELETE_CLIENT',
  CLIENTE_DELETED_SUCCESS: 'CLIENTE_DELETED_SUCCESS',

  UPDATE_RESIDENCE: 'UPDATE_RESIDENCE',
  RESIDENCE_UPDATED_SUCCESS: 'RESIDENCE_UPDATED_SUCCESS',

  DELETE_RESIDENCE: 'DELETE_RESIDENCE',
  RESIDENCE_DELETED_SUCCESS: 'RESIDENCE_DELETED_SUCCESS',
};
